[package]
name = "advent_of_code_day_1"
version = "0.1.0"
authors = ["Markus Gögele (AdronTech)"]
edition = "2021"

[dependencies]
anyhow = "1.0.75"
colored = "2.0.4"
itertools = "0.11.0"
lazy_static = "1.4.0"
nom = "7.1.3"
nom-supreme = "0.8.0"
regex = "1.10.2"
