[package]
name = "advent_of_code_day_7"
version = "0.1.0"
authors = ["Markus Gögele (AdronTech)"]
edition = "2021"

[dependencies]
anyhow = "1.0.75"
colored = "2.0.4"
env_logger = "0.10.1"
itertools = "0.11.0"
log = "0.4.20"
nom = "7.1.3"
nom-supreme = "0.8.0"
